In [1]:
import torch

In [4]:
tensor = torch.rand(7,7)
tensor, tensor.shape

(tensor([[0.1236, 0.4497, 0.1922, 0.5841, 0.2526, 0.7737, 0.1837],
         [0.7520, 0.9086, 0.3088, 0.2477, 0.6239, 0.6494, 0.7538],
         [0.2409, 0.4799, 0.9822, 0.0518, 0.3511, 0.1791, 0.7110],
         [0.7581, 0.3480, 0.3246, 0.8598, 0.9977, 0.4583, 0.2426],
         [0.2315, 0.4161, 0.1777, 0.2314, 0.3831, 0.0129, 0.1527],
         [0.8503, 0.9373, 0.8716, 0.8800, 0.7493, 0.7417, 0.8145],
         [0.8828, 0.6747, 0.7564, 0.3179, 0.0897, 0.5590, 0.8598]]),
 torch.Size([7, 7]))

In [6]:
tensor_2 = torch.rand(1,7)
tensor_2

tensor([[0.5833, 0.8154, 0.2094, 0.4648, 0.1487, 0.0489, 0.4632]])

In [7]:
mat = torch.matmul(tensor, tensor_2.T)
print(mat)

tensor([[0.9110],
        [1.8331],
        [1.1520],
        [1.4767],
        [0.7474],
        [2.3769],
        [1.8102]])
